env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
  - "plugin:@typescript-eslint/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-empty-function": off
  comma-dangle: off
  quotes: error
  semi: off
  space-before-function-paren: off
  prefer-const: off
  react/display-name: off
